"""
Phase 14 Creative Workforce Director
-------------------------------------
Executive director interface converting client/brand objectives into high-level organizational work plans.
Coordinates delegation across Strategy, Creative, Intelligence, Content, and Quality departments
without originating execution authorization.
"""

from typing import List, Dict, Any, Optional
import uuid

from src.creative_workforce.organization_models import WorkforceAssignment
from src.creative_workforce.delegation import WorkforceDelegationEngine
from src.creative_workforce.exceptions import InvalidWorkforceRequestError

class WorkforcePlan:
    """Immutable workforce plan generated by the CreativeWorkforceDirector."""

    def __init__(
        self,
        plan_id: str,
        client_id: str,
        brand_id: str,
        campaign_title: str,
        objective: str,
        assignments: List[WorkforceAssignment],
    ):
        self.plan_id = plan_id
        self.client_id = client_id
        self.brand_id = brand_id
        self.campaign_title = campaign_title
        self.objective = objective
        self.assignments = assignments

class CreativeWorkforceDirector:
    """Executive director converting client objectives into workforce work plans."""

    def __init__(self, delegation_engine: Optional[WorkforceDelegationEngine] = None):
        self.delegation_engine = delegation_engine or WorkforceDelegationEngine()
        self._plans: Dict[str, WorkforcePlan] = {}

    def formulate_workforce_plan(
        self,
        client_id: str,
        brand_id: str,
        campaign_title: str,
        objective: str,
        custom_task_specs: Optional[List[Dict[str, Any]]] = None,
    ) -> WorkforcePlan:
        """Formulates a comprehensive organizational workforce plan for a client campaign."""
        if not client_id or not brand_id or not campaign_title:
            raise InvalidWorkforceRequestError("client_id, brand_id, and campaign_title are required.")

        plan_id = f"plan-{uuid.uuid4().hex[:8]}"
        mission_id = f"m-{uuid.uuid4().hex[:8]}"
        campaign_id = f"cmp-{uuid.uuid4().hex[:8]}"

        assignments = self.delegation_engine.decompose_objective(
            client_id=client_id,
            brand_id=brand_id,
            campaign_id=campaign_id,
            mission_id=mission_id,
            objective=objective,
            task_specs=custom_task_specs,
        )

        plan = WorkforcePlan(
            plan_id=plan_id,
            client_id=client_id,
            brand_id=brand_id,
            campaign_title=campaign_title,
            objective=objective,
            assignments=assignments,
        )
        self._plans[plan_id] = plan
        return plan

    def get_plan(self, plan_id: str) -> Optional[WorkforcePlan]:
        """Retrieves a formulated workforce plan."""
        return self._plans.get(plan_id)
